### ISSUE TITLE
在某些特例中，求函数与x,y轴的交点出现语法错误

### ISSUE THREAD

**Issue by Kevin0217168** [Kevin0217168/HanShu#1]
<img width="544" alt="批注 2020-08-15 161802" src="https://user-images.githubusercontent.com/54020766/90308546-eace1080-df12-11ea-94e9-b4eb3cd8e2a6.png">

```python
exp = "y=-3x-5"
coordinatesOnTheXY(exp)

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    coordinatesOnTheXY(exp)
  File "D:\ME\Pychram_edu_2019\HanShu\model.py", line 149, in coordinatesOnTheXY
    x1 = list(solveQuestions([expression1], 'x').items())[0][1]
  File "D:\ME\Pychram_edu_2019\HanShu\model.py", line 128, in solveQuestions
    ex.append(eval(expressions[n]))
  File "<string>", line 1
    0-(-3x-5)
         ^
SyntaxError: invalid syntax
```

**Comment by Kevin0217168** [comment]
> 0-(-3x-5)
>       ^

初步判断应是表达式未转换为计算机格式引起的
3x => 3*x
晚上修复
